languge: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t bohato/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bohato/react-test npm test

after_success:
    - docker build -t bohato/multi-client ./client
    - docker build -t bohato/multi-nginx ./nginx
    - docker build -t bohato/multi-server ./server
    - docker build -t bohato/multi-worker ./worker
    # Log in to the docker CLI    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push bohato/multi-client
    - docker push bohato/multi-nginx
    - docker push bohato/multi-server
    - docker push bohato/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-540392531610
    bucket_path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY